const countries = {
    "en-GB": "English",
    "es-ES": "Spanish",
    "fr-FR": "French",
    "pt-PT": "Portuguese",
    "ro-RO": "Romanian",
    "de-DE": "German",
    "de-AT": "Austrian German",
    "it-IT": "Italian",
    "fi-FI": "Finnish",
    "el-GR": "Greek",
    "hu-HU": "Hungarian",
    "ru-RU": "Russian",
    "be-BY": "Belarusian",
    "sr-RS": "Serbian",
    "uk-UA": "Ukrainian",
    "sv-SE": "Swedish",
    "sv-fi": "Finland Swedish",
    "bs-BA": "Bosnian",
    "mk-MK": "Macedonian",
    "hr-HR": "Croatian",
    "cnr-ME": "Montenegrin",
    "sq-AL": "Albanian",
    "tr-TR": "Turkish",
    "tr-CY": "Cypriot Turkish",
    "no-NO": "Norwegian",
    "ga-IE": "Irish",
    "gd-GB": "Scottish Gaelic",
    "kl-GL": "Greenlandic",
    "mt-MT": "Maltese",
    "me": "Montengrin",
    "se-NO": "Northern Sámi",
    "is-IS": "Icelandic",
    "pl-PL": "Polish",
    "nl-NL": "Dutch",
    "eu-ES": "Basque",
    "ast-ES": "Asturian",
    "lb-LU": "Luxembourgish",
    "ca-ES": "Catalan",
    "rm-CH": "Romansh",
    "cs-CZ": "Czech",
    "sk-SK": "Slovak",
    "ka-GE": "Georgian",
    "az-AZ": "Azeri"
}
